apps/accreditation/urls.py
from django.urls import path, re_path
from apps.accreditation.views import accreditationCreate, accreditationIndex, accreditationView, accreditationUpdate, TypeCreate, accreditationSearch, accreditationForm, AcreditationAPIList

urlpatterns = [
    path('', accreditationIndex.as_view(), name='accreditation.index'),
    path('search/', accreditationSearch.as_view(), name='accreditation.search'),
    path('form/<int:pk>', accreditationForm.as_view(), name='accreditation.form'),
    path('api/search/', AcreditationAPIList.as_view(), name='accreditation.api.view'),
    path('create/', accreditationCreate.as_view(), name='accreditation.create'),
    path('view/<str:pk>', accreditationView.index, name='accreditation.view'),
    path('update/<str:pk>', accreditationUpdate.as_view(), name='accreditation.update'),
    path('type/create/', TypeCreate.as_view(), name="accreditation.type_create")
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('certificate/', include("apps.certify.urls")),
    path('accreditation/', include("apps.accreditation.urls")),
    path('tools/', include("apps.includes.sidebar.urls")),
    path('people/', include("apps.people.urls")),
    path('administration/', include("apps.administration.urls")),
    path('validations/', include("apps.validations.urls")),
    path('reports/', include("apps.reports.urls")),
    path('control/', include("apps.control.urls")),
    path('vehicles/', include("apps.vehicles.urls")),
    path('business/', include("apps.business.urls")),
    path('modules/', include("apps.modules.urls")),
    path('inspections/', include("apps.inspections.urls")),
    path('admin/', admin.site.urls),          # Django admin route
    path("login/", include("core.login.urls")), # Auth routes - login / register
    path("tablero/", include("apps.home.urls")),            # UI Kits Html files
    path("", include("apps.web.urls"))            # UI Kits Html files
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accreditation/models.py
from django.db import models
from apps.business.models import business
from apps.validations.models import routes
from apps.vehicles.models import  vehicles, types
# Create your models here.

class accreditation_type(models.Model):
    COLOR_FILED = (
        ('success', 'success'),
        ('danger', 'danger'),
        ('warning', 'warning'),
        ('dark', 'dark'),
        ('primary', 'primary'),
        ('secondary', 'secondary'),
        ('grey', 'grey')
    )
    ICON_FILED = (
        ('verified_user','verified_user'),
        ('health_and_safety','verified_user'),
        ('security','verified_user'),
        ('shield','verified_user'),
        ('policy','verified_user'),
        ('privacy_tip','verified_user'),
        ('gpp_maybe','verified_user'),
        ('gpp_bad','verified_user'),
        ('safety_check','verified_user'),
        ('add_moderator','verified_user'),
        ('remove_moderator','verified_user')
    )
    name = models.TextField(max_length=150, unique=True)
    description = models.TextField(max_length=255, null=True, blank=True)
    color = models.TextField(max_length=50, choices=COLOR_FILED, null=True, blank=True)
    icon = models.TextField(max_length=60, choices=ICON_FILED, null=True, blank=True)
    status = models.BooleanField(null=True)

    def __str__(self):
        return self.name

class accreditation(models.Model):
    STATUSFIELD = (
        ('CUMPLE', 'CUMPLE'),
        ('NO CUMPLE', 'NO CUMPLE'),
        ('PENDIENTE', 'PENDIENTE')
    )
    STATUS = (
        ('ACREDITADO', 'ACREDITADO'),
        ('PENDIENTE', 'PENDIENTE'),
        ('RETIRADO', 'RETIRADO')
    )
    plate = models.ForeignKey(vehicles, null=True, blank=True, on_delete=models.CASCADE)
    route = models.ForeignKey(routes, null=True, blank=True, on_delete=models.CASCADE)
    legal_requirements = models.CharField(max_length=20, choices=STATUSFIELD)
    technical_requirements = models.CharField(max_length=20, choices=STATUSFIELD)
    mechanical_inspection = models.CharField(max_length=20, choices=STATUSFIELD)
    insurance = models.CharField(max_length=20, choices=STATUSFIELD)
    accreditation_card = models.BooleanField()
    year_of_production = models.CharField(max_length=4,null=True, blank=True)
    typology = models.ForeignKey(types, null=True, blank=True, on_delete=models.CASCADE)
    permit_number = models.CharField(max_length=5, null=True, blank=True)
    remark = models.TextField(null=True, blank=True)
    bussines = models.ForeignKey(business, null=True, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=STATUS)
    type = models.ForeignKey(accreditation_type, null=True, blank=True, on_delete=models.CASCADE)
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    delete_at = models.DateTimeField(null=True, blank=True)

apps/accreditation/forms.py
from django import forms

from apps.accreditation.models import accreditation, accreditation_type
class typeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['autofocus']= True
    class Meta:
        model = accreditation_type

        fields = '__all__'
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control  form-control-lg', 'autocomplete': 'off'}),
            'description' : forms.TextInput(attrs={'class':'form-control  form-control-sm', 'autocomplete': 'off'}),
            'status' : forms.CheckboxInput(attrs={'class' : 'form-check-input'}),
            'color' : forms.Select(attrs={'class' : 'form-control  form-control-sm select-single'})
        }


class accreditationsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['permit_number'].widget.attrs['autofocus']= True

    class Meta:
        model = accreditation

        fields = [
            'plate',
            'route',
            'legal_requirements',
            'technical_requirements',
            'mechanical_inspection',
            'insurance',
            'accreditation_card',
            'year_of_production',
            'typology',
            'permit_number',
            'remark',
            'bussines',
            'status',
            'type',
            'enabled'
        ]

        widgets = {
            'plate' : forms.Select(attrs={'class':'form-control w-100 select-single', 'style':'width: 100%'}),
            'route' : forms.Select(attrs={'class':'form-control  form-control-sm select-single'}),
            'legal_requirements' : forms.Select(attrs={'class':'form-control  form-control-sm'}),
            'technical_requirements' : forms.Select(attrs={'class':'form-control  form-control-sm'}),
            'mechanical_inspection' : forms.Select(attrs={'class':'form-control  form-control-sm'}),
            'insurance' : forms.Select(attrs={'class':'form-control  form-control-sm'}),
            'accreditation_card' : forms.CheckboxInput(attrs={'class':'form-check-input mt-2', 'placeholder':'estado'}),
            'year_of_production' : forms.TextInput(attrs={'class':'form-control  form-control-sm'}),
            'typology' : forms.Select(attrs={'class':'form-control  form-control-sm select-single'}),
            'permit_number': forms.TextInput(attrs={'class':'form-control form-control-lg', 'autocomplete': 'off'}),
            'remark' : forms.Textarea(attrs={'class':'form-control', 'rows' : '5'}),
            'bussines' : forms.Select(attrs={'class':'form-control  form-control-sm select-single'}),
            'status' : forms.Select(attrs={'class':'form-control  form-control-sm'}),
            'type' : forms.Select(attrs={'class':'form-control  form-control-sm select-single', 'style': 'width: 83%'}),
            'enabled' : forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }

apps/accreditation/views.py
from apps.validations.models import procedure
from rest_framework.generics import CreateAPIView, ListAPIView
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.shortcuts import render
from django.views.generic import UpdateView, ListView, CreateView, TemplateView, FormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core import serializers

from apps.accreditation.forms import accreditationsForm, typeForm
from apps.accreditation.models import accreditation, accreditation_type
from apps.accreditation.mixins import ValidatePermissionRequiredMixin
from apps.includes.sidebar.models import Sidebar
from apps.vehicles.models import vehicles
from .serializers import serialiazerType, serializerAcreditation
# Create your views here.

class accreditationIndex(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    login_url = '/login/'
    model = accreditation
    template_name  = 'accreditation/index.html'
    paginate_by = 50

    def get_queryset(self):
        return accreditation.objects.order_by('plate').filter(delete_at__isnull=True)

    def get_context_data(self, **kwargs):
        context = super(accreditationIndex, self).get_context_data(**kwargs)
        context['segment'] = 'accreditation'
        context['sidebars'] = Sidebar.objects.all()
        context['title'] = Sidebar.objects.get(id=10)
        context['page'] = 'Crear Propietario'
        return context

class accreditationCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = accreditation
    template_name = 'accreditation/create.html'
    form_class = accreditationsForm
    success_url = reverse_lazy('accreditation.index')
    success_message = 'Doc successfully created!'
    error_message = "Error saving the Doc, check fields below."

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request,  *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'no ha ingresado a ninguna opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

class accreditationView(HttpResponse):
    @login_required(login_url="/login/")
    def index(request, pk):
        sidebar = Sidebar.objects.all()
        title = Sidebar.objects.get(id=10)
        ac = accreditation.objects.get(id=pk)

        context = {'segment': 'business', 'sidebars': sidebar, 'title': title, 'page':'Empresas', 'accreditation': ac}
        html_template = loader.get_template('accreditation/view.html')
        return HttpResponse(html_template.render(context, request))

class accreditationUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = accreditation
    template_name = 'accreditation/update.html'
    form_class = accreditationsForm
    success_url = reverse_lazy('accreditation.index')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                form = self.get_form()
                if form.is_valid():
                    instance = form.save()
                    data['success'] = serializers.serialize('json', [ instance, ])
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'no ha ingresado a ninguna opcion'
            #data = accreditation_type.post(id=request.POST['id']).toJson().toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super(accreditationUpdate, self).get_context_data(**kwargs)
        context['segment'] = 'accreditation'
        context['sidebars'] = Sidebar.objects.all()
        context['title'] = Sidebar.objects.get(id=10)
        context['page'] = 'Actualizar acreditacion'
        context['accreditation'] = accreditation.objects.all().get(id = self.kwargs['pk'])
        context['pk'] = self.kwargs['pk']
        return context

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class TypeCreate(CreateView):
    model = accreditation_type
    form_class = typeForm
    success_url = reverse_lazy('accreditation.create')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    instance = form.save()
                    data['success'] = serializers.serialize('json', [ instance, ])
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'no ha ingresado a ninguna opcion'
            #data = accreditation_type.post(id=request.POST['id']).toJson().toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

class accreditationSearch(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'accreditation/search.html'

    def get_context_data(self, **kwargs):
        context = super(accreditationSearch, self).get_context_data(**kwargs)
        context['segment'] = 'accreditation'
        context['sidebars'] = Sidebar.objects.all()
        context['title'] = Sidebar.objects.get(id=10)
        context['page'] = 'Actualizar acreditacion'
        return context

class accreditationForm(LoginRequiredMixin, FormView):
    login_url = '/login/'
    template_name = 'accreditation/create.html'
    form_class = accreditationsForm

    def get_procedure(self):
        try:
            pros = procedure.objects.all().get(id = self.kwargs['pk'])
        except accreditation.DoesNotExist:
            pros = None
        return pros

    def get_mechanical_inspection(self):
        try:
            proc = procedure.objects.all().get(id = self.kwargs['pk'])
            if proc:
                if proc.soat_status == 'VIGENTE':
                    status = 'CUMPLE'
                else:
                    if proc.soat_status == 'NO VIGENTE':
                        status = 'NO CUMPLE'
                    else:
                        status = 'PENDIENTE'
        except procedure.DoesNotExist:
            proc = None
        return status

    def get_mechanical_inspection(self):
        proc = procedure.objects.all().get(id = self.kwargs['pk'])
        if proc:
            if proc.citv_status == 'VIGENTE':
                status = 'CUMPLE'
            else:
                if proc.citv_status == 'NO VIGENTE':
                    status = 'NO CUMPLE'
                else:
                    status = 'PENDIENTE'
        return status

    def get_technical_requirements(self):
        try:
            proc = procedure.objects.all().get(id = self.kwargs['pk'])
            if proc:
                if proc.src_status == 'VIGENTE' and proc.citv_status == 'VIGENTE' and proc.bonding_contract and proc.check_sistran == True:
                    status = 'CUMPLE'
                else:
                    if proc.src_status == 'NO VIGENTE' or proc.svct_status == 'NO VIGENTE' or proc.bonding_contract or proc.check_sistran == False:
                        status = 'NO CUMPLE'
                    else:
                        status = 'OBSERVADO'
        except procedure.DoesNotExist:
            proc = None
        return status

    def get_context_data(self, **kwargs):
        context = super(accreditationForm, self).get_context_data(**kwargs)
        context['segment'] = 'accreditation'
        context['sidebars'] = Sidebar.objects.all()
        context['title'] = Sidebar.objects.get(id=10)
        context['procedure'] = self.get_procedure()
        context['insurance'] = self.get_mechanical_inspection()
        context['mechanical_inspection'] = self.get_mechanical_inspection()
        context['technical_requirements'] = self.get_technical_requirements()
        context['page'] = 'Actualizar acreditacion'
        return context

class AcreditationAPIList(ListAPIView):
    serializer_class = serializerAcreditation

    def get_queryset(self):
        kword = self.request.query_params.get('kword', '')
        return accreditation.objects.filter(plate = kword)

apps/templates/accreditation/update.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="/static/assets/css/select2.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="container-fluid p-1">
        <div class="bg-light max-height-vh-90">
            <div class="position-sticky z-index-sticky top-0 me-3 scrollspy-example" data-bs-spy="scroll" data-bs-offset="0">
                {{error_message}}
                <form action="{% url 'accreditation.update' pk=pk %}" id="id_form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="update">
                    <nav class="navbar shadow-lg rounded navbar-expand-lg z-index-3 position-fixed w-form pt-4 blur-gradient-primary start-0 end-0 mx-0 bg-light">
                        <div class="container-fluid ps-2 pe-0">
                            <a href="{% url 'business.index' %}" class="btn btn-link px-1 me-3" @click="$emit('close')">
                                <i class="material-icons opacity-10">close</i>
                            </a>
                            <div class="navbar-brand font-weight-bolder ms-lg-0 ms-3 brand-form">
                                Actualizar registro {{pk}}
                                <input type="hidden" name="id" id="id_id" value="{{pk}}">
                            </div>
                            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon mt-2">
                                    <span class="navbar-toggler-bar bar1"></span>
                                    <span class="navbar-toggler-bar bar2"></span>
                                    <span class="navbar-toggler-bar bar3"></span>
                                </span>
                            </button>
                            <div class="collapse navbar-collapse" id="navigation">
                                <ul class="navbar-nav mx-auto">
                                    <li class="nav-item">
                                    </li>
                                </ul>
                                <ul class="navbar-nav d-lg-flex d-none">
                                    <li class="nav-item d-none">
                                        <a href="#" class="btn me-1 bg-gradient-success" type="button">
                                            <i class="material-icons opacity-10">sync_alt</i>
                                            Sincronizar datos
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <button class="btn me-1 bg-gradient-info" type="submit">
                                            <i class="material-icons opacity-10">check</i>
                                            Guardar registro
                                        </button>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <div class="container-fluid">
                        <div class="row my-3">
                            <div class="col-md-4">
                                <div class="card h-100">
                                    <div class="card-header pb-0">
                                        <h6>Datos del  principales </h6>
                                    </div>
                                    <div class="card-body p-3 pt-0">
                                        <div class="input-group input-group-lg input-group-outline mb-4">
                                            <label class="form-label">Número de permiso o TAPSIT</label>
                                            {{form.permit_number}}
                                        </div>
                                        <div class="input-group input-group-static mb-4">
                                            <label class="ms-0">Tipo de acreditacion</label>
                                            {{form.type}}
                                            <button class="btn btn-sm bg-gradient-success mb-0 px-3" type="button" id="type-modal" data-bs-toggle="modal" data-bs-target="#type-accreditation">
                                                <span class="material-icons">
                                                    add
                                                </span>
                                            </button>
                                        </div>
                                        <div class="input-group input-group-static mb-4">
                                            <label>Tipologia</label>
                                            {{form.typology}}
                                        </div>
                                        <div class="input-group input-group-static mb-4">
                                            <label>Placa vehicular</label>
                                            {% if accreditation %}
                                                <input type="text" name="plate" id="id_plate" value="{{accreditation.plate}}" class="form-control" readonly>
                                            {% else %}
                                                {{form.plate}}
                                            {% endif %}
                                        </div>
                                        <div class="input-group input-group-sm input-group-static mb-4">
                                            <label>Año de produccion</label>
                                            {% if procedure %}
                                                <input type="text" name="year_of_production" id="id_year_of_production" value="{{procedure.license_plate.year_of_production}}" class="form-control" readonly>
                                            {% else %}
                                                {{form.year_of_production}}
                                            {% endif %}
                                        </div>
                                        <div class="input-group input-group-static mb-4">
                                            <label>Ruta</label>
                                            {% if accreditation %}
                                                <input type="hidden" name="route" id="id_route" value="{{accreditation.route_id}}" readonly>
                                                <input type="text" name="route_name" id="id_route_name" value="{{accreditation.route.route}} - {{accreditation.route.concession}}" class="form-control" readonly>
                                            {% else %}
                                                {{form.route}}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="card h-100">
                                    <div class="card-header pb-0">
                                        <h6>Datos del  generales</h6>
                                    </div>
                                    <div class="card-body p-3 pt-0">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="input-group input-group-static mb-4  is-valid">
                                                    <label>Requerimientos legales</label>
                                                    {{form.legal_requirements}}
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="input-group input-group-static mb-4">
                                                    <label>Requerimientos Tecnico</label>
                                                    {% if procedure %}
                                                        <input name="technical_requirements" id="id_technical_requirements" class="form-control" type="text" value="{{ technical_requirements }}">
                                                    {% else %}
                                                        {{form.technical_requirements}}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="input-group input-group-static mb-4">
                                                    <label>Inspeccion mecanica</label>
                                                    {% if procedure %}
                                                        <input name="mechanical_inspection" id="id_mechanical_inspection" class="form-control" type="text" value="{{ mechanical_inspection }}">
                                                    {% else %}
                                                        {{form.mechanical_inspection}}
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="input-group input-group-static mb-4">
                                                    <label>Seguro</label>
                                                    {% if procedure %}
                                                        <input name="insurance" id="id_insurance" class="form-control" type="text" value="{{insurance}}">
                                                    {% else %}
                                                        {{form.insurance}}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="input-group input-group-static mb-4">
                                            <label>Empresa</label>
                                            {% if procedure %}
                                                <input type="hidden" name="bussines" id="id_bussines" value="{{procedure.license_plate.business_id}}" readonly>
                                                <input type="text" name="bussines_name" id="id_route_name" value="{{procedure.license_plate.business}}" class="form-control" readonly>
                                            {% else %}
                                                {{form.bussines}}
                                            {% endif %}
                                        </div>
                                        <div class="input-group input-group-dynamic">
                                            <label>Observaciones</label>
                                            {{form.remark}}
                                        </div>
                                        <div class="form-check">
                                            {{form.accreditation_card}}
                                            <label class="custom-control-label" for="customCheck1">Targeta de acreditacion</label>
                                        </div>
                                        <div class="form-check">
                                            {{form.enabled}}
                                            <label class="custom-control-label" for="customCheck1">habilitado</label>
                                        </div>
                                        <div class="form-check">
                                            <label>Estado</label>
                                            {{form.status}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="/static/assets/js/plugins/chartjs.min.js"></script>
<script src="/static/assets/js/plugins/dropzone.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
<script src="/static/assets/js/select2.min.js"></script>
<script src="/static/assets/vue/forms.js"></script>
<script>
    $(document).ready(function() {
        $('.select-single').select2();
    });
</script>
{% endblock javascripts %}